In [411]:
import pandas as pd

In [412]:
df = pd.read_csv("TestCricketAvgData.csv")
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258+,2
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
11,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
12,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54
13,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
14,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107+,11
15,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7
16,Saud Shakeel (PAK),2022-2024,12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2
20,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24
21,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1
22,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
23,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
24,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6
25,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69
26,HC Brook (ENG),2022-2024,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
41,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
42,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
43,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28
44,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29
45,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84
46,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3
47,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
48,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
49,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12
50,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11
51,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0
52,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91
53,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
55,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
56,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
57,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20
58,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1
59,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,NaN,5,6,3,51+,0
60,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
61,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1
62,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
63,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
64,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
65,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
66,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [413]:
#Rename columns

In [414]:
df = df.rename(columns = {"Mat": "Matches", "Inns": "Innings", "NO": "Not_Outs", "HS": "High_Score", "Ave": "Average_Score", "BF": "Balls_Faced", "SR": "Batting_Strike_Rate"})

In [415]:
#finding the null values

In [416]:
df.isnull().any()

Player                 False
Span                   False
Matches                False
Innings                False
Not_Outs               False
Runs                   False
High_Score             False
Average_Score          False
Balls_Faced             True
Batting_Strike_Rate     True
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [417]:
#finding the NaN values in specific field

In [418]:
df[df['Balls_Faced'].isna() == True]

,Player,Span,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258+,2
14,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107+,11
59,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,NaN,5,6,3,51+,0

In [419]:
#replacing 0 for null values

In [420]:
df["Balls_Faced"] = df["Balls_Faced"].fillna(0)

In [421]:
df["Batting_Strike_Rate"] = df["Batting_Strike_Rate"].fillna(0)

In [422]:
df[df['Player']=="ED Weekes (WI)"]

,Player,Span,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.0,15,19,6,258+,2

In [423]:
#finding the duplicates values

In [424]:
df.duplicated()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42     True
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55     True
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
dtype: bool

In [425]:
df[df['Player'].duplicated() == 1]

,Player,Span,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
42,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
55,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [426]:
df[df['Player'].isin(["GA Headley (WI)","JH Kallis (ICC/SA)","JE Root (ENG)","V Kohli (IND)"])]

,Player,Span,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
41,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
42,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
55,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [427]:
#drop duplicate values

In [428]:
df = df.drop_duplicates()

In [429]:
df

,Player,Span,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
11,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
12,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54
13,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
14,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11
15,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7
16,Saud Shakeel (PAK),2022-2024,12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2
20,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24
21,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1
22,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
23,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
24,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6
25,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69
26,HC Brook (ENG),2022-2024,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
41,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
43,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28
44,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29
45,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84
46,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3
47,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
48,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
49,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12
50,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11
51,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0
52,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91
53,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
56,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
57,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20
58,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1
59,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,0.00,5,6,3,51+,0
60,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
61,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1
62,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
63,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
64,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
65,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
66,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [430]:
#split the SPan fields

In [431]:
df

,Player,Span,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
11,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
12,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54
13,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
14,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11
15,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7
16,Saud Shakeel (PAK),2022-2024,12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2
20,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24
21,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1
22,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
23,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
24,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6
25,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69
26,HC Brook (ENG),2022-2024,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
41,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
43,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28
44,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29
45,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84
46,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3
47,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
48,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
49,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12
50,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11
51,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0
52,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91
53,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
56,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
57,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20
58,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1
59,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,0.00,5,6,3,51+,0
60,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
61,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1
62,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
63,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
64,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
65,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
66,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [432]:
df['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2015, 2016]
2     [1963, 1970]
3     [1930, 1954]
5     [1924, 1935]
6     [1931, 1939]
7     [1955, 1968]
8     [1948, 1958]
9     [1927, 1947]
10    [1954, 1974]
11    [2000, 2015]
12    [2010, 2024]
13    [1908, 1930]
14    [1948, 1960]
15    [1937, 1955]
16    [2022, 2024]
17    [1995, 2013]
19    [1921, 1929]
20    [2010, 2024]
21    [1968, 1973]
22    [1993, 1995]
23    [1970, 1984]
24    [1935, 1951]
25    [1989, 2013]
26    [2022, 2024]
27    [1990, 2006]
28    [1976, 1993]
29    [1996, 2012]
30    [1998, 2010]
31    [2000, 2017]
32    [1995, 2012]
33    [1920, 1929]
34    [1992, 2002]
35    [2005, 2013]
36    [1994, 2015]
37    [1971, 1987]
38    [1985, 2004]
39    [1994, 2009]
40    [2004, 2018]
41    [2012, 2024]
43    [1978, 1994]
44    [2019, 2024]
45    [1974, 1991]
46    [1937, 1957]
47    [1997, 2014]
48    [1992, 2007]
49    [2018, 2024]
50    [1948, 1963]
51    [1911, 1928]
52    [2001, 2013]
53    [2019, 2021]
54    [2011, 2024]
56    [2004, 2015]
57    [1961, 1966]
58    [1929, 1949]
59    [1893, 1905]
60    [2001, 2013]
61    [1948, 1963]
62    [1965, 1981]
63    [2002, 2014]
64    [1924, 1934]
65    [1930, 1938]
66    [1928, 1934]
Name: Span, dtype: object

In [433]:
df['Span'].str.split(pat = '-').str[1]

0     1948
1     2016
2     1970
3     1954
5     1935
6     1939
7     1968
8     1958
9     1947
10    1974
11    2015
12    2024
13    1930
14    1960
15    1955
16    2024
17    2013
19    1929
20    2024
21    1973
22    1995
23    1984
24    1951
25    2013
26    2024
27    2006
28    1993
29    2012
30    2010
31    2017
32    2012
33    1929
34    2002
35    2013
36    2015
37    1987
38    2004
39    2009
40    2018
41    2024
43    1994
44    2024
45    1991
46    1957
47    2014
48    2007
49    2024
50    1963
51    1928
52    2013
53    2021
54    2024
56    2015
57    1966
58    1949
59    1905
60    2013
61    1963
62    1981
63    2014
64    1934
65    1938
66    1934
Name: Span, dtype: object

In [434]:
df["Start_Year"] = df["Span"].str.split(pat = '-').str[0]

In [435]:
df["End_Year"] = df["Span"].str.split(pat = '-').str[1]

In [436]:
df

,Player,Span,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974
11,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
12,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
13,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930
14,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960
15,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955
16,Saud Shakeel (PAK),2022-2024,12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1,2022,2024
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929
20,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
21,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973
22,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
23,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
24,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951
25,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013
26,HC Brook (ENG),2022-2024,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26,2022,2024
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
41,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44,2012,2024
43,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
44,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
45,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991
46,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957
47,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
48,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
49,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
50,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963
51,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0,1911,1928
52,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
53,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
56,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015
57,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20,1961,1966
58,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1,1929,1949
59,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,0.00,5,6,3,51+,0,1893,1905
60,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
61,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963
62,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
63,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
64,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
65,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
66,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [437]:
#drop Span field

In [438]:
df = df.drop(['Span'], axis = 1)

In [439]:
df.head()

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935

In [440]:
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935
6,E Paynter (ENG),20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939
7,KF Barrington (ENG),82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968
8,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958
9,WR Hammond (ENG),85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947
10,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974
11,KC Sangakkara (SL),134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
12,SPD Smith (AUS),109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
13,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930
14,CL Walcott (WI),44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960
15,L Hutton (ENG),79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955
16,Saud Shakeel (PAK),12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1,2022,2024
17,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
19,GE Tyldesley (ENG),14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929
20,KS Williamson (NZ),100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
21,CA Davis (WI),15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973
22,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
23,GS Chappell (AUS),87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
24,AD Nourse (SA),34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951
25,SR Tendulkar (IND),200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013
26,HC Brook (ENG),18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26,2022,2024
27,BC Lara (ICC/WI),131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
28,Javed Miandad (PAK),124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993
29,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
30,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
31,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
32,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
33,J Ryder (AUS),20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929
34,A Flower (ZIM),63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
35,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
36,S Chanderpaul (WI),164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
37,SM Gavaskar (IND),125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987
38,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
39,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
40,AB de Villiers (SA),114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
41,JE Root (ENG),146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44,2012,2024
43,AR Border (AUS),156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
44,DJ Mitchell (NZ),23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
45,IVA Richards (WI),121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991
46,DCS Compton (ENG),78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957
47,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
48,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
49,M Labuschagne (AUS),50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
50,FMM Worrell (WI),51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963
51,CP Mead (ENG),17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0,1911,1928
52,V Sehwag (ICC/IND),104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
53,Abid Ali (PAK),16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
54,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
56,MJ Clarke (AUS),115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015
57,KC Bland (SA),21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20,1961,1966
58,B Mitchell (SA),42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1,1929,1949
59,Hon.FS Jackson (ENG),20,33,4,1415,144*,48.79,0,0.00,5,6,3,51+,0,1893,1905
60,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
61,RN Harvey (AUS),79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963
62,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
63,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
64,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
65,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
66,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [441]:
df["Player"].str.split(pat = '(')

0             [DG Bradman , AUS)]
1               [AC Voges , AUS)]
2              [RG Pollock , SA)]
3              [GA Headley , WI)]
5            [H Sutcliffe , ENG)]
6              [E Paynter , ENG)]
7          [KF Barrington , ENG)]
8               [ED Weekes , WI)]
9             [WR Hammond , ENG)]
10              [GS Sobers , WI)]
11          [KC Sangakkara , SL)]
12             [SPD Smith , AUS)]
13              [JB Hobbs , ENG)]
14             [CL Walcott , WI)]
15              [L Hutton , ENG)]
16          [Saud Shakeel , PAK)]
17          [JH Kallis , ICC/SA)]
19          [GE Tyldesley , ENG)]
20          [KS Williamson , NZ)]
21               [CA Davis , WI)]
22             [VG Kambli , IND)]
23           [GS Chappell , AUS)]
24              [AD Nourse , SA)]
25          [SR Tendulkar , IND)]
26              [HC Brook , ENG)]
27            [BC Lara , ICC/WI)]
28         [Javed Miandad , PAK)]
29          [R Dravid , ICC/IND)]
30       [Mohammad Yousuf , PAK)]
31           [Younis Khan , PAK)]
32            [RT Ponting , AUS)]
33               [J Ryder , AUS)]
34              [A Flower , ZIM)]
35            [MEK Hussey , AUS)]
36          [S Chanderpaul , WI)]
37           [SM Gavaskar , IND)]
38              [SR Waugh , AUS)]
39             [ML Hayden , AUS)]
40         [AB de Villiers , SA)]
41               [JE Root , ENG)]
43             [AR Border , AUS)]
44            [DJ Mitchell , NZ)]
45           [IVA Richards , WI)]
46           [DCS Compton , ENG)]
47       [DPMD Jayawardene , SL)]
48    [Inzamam-ul-Haq , ICC/PAK)]
49         [M Labuschagne , AUS)]
50            [FMM Worrell , WI)]
51               [CP Mead , ENG)]
52          [V Sehwag , ICC/IND)]
53              [Abid Ali , PAK)]
54               [V Kohli , IND)]
56             [MJ Clarke , AUS)]
57               [KC Bland , SA)]
58             [B Mitchell , SA)]
59        [Hon.FS Jackson , ENG)]
60         [TT Samaraweera , SL)]
61             [RN Harvey , AUS)]
62            [KD Walters , AUS)]
63           [GC Smith , ICC/SA)]
64           [WH Ponsford , AUS)]
65             [SJ McCabe , AUS)]
66            [DR Jardine , ENG)]
Name: Player, dtype: object

In [442]:
df["Country"] = df["Player"].str.split(pat = '(').str[1]

In [443]:
df["Country"]

0         AUS)
1         AUS)
2          SA)
3          WI)
5         ENG)
6         ENG)
7         ENG)
8          WI)
9         ENG)
10         WI)
11         SL)
12        AUS)
13        ENG)
14         WI)
15        ENG)
16        PAK)
17     ICC/SA)
19        ENG)
20         NZ)
21         WI)
22        IND)
23        AUS)
24         SA)
25        IND)
26        ENG)
27     ICC/WI)
28        PAK)
29    ICC/IND)
30        PAK)
31        PAK)
32        AUS)
33        AUS)
34        ZIM)
35        AUS)
36         WI)
37        IND)
38        AUS)
39        AUS)
40         SA)
41        ENG)
43        AUS)
44         NZ)
45         WI)
46        ENG)
47         SL)
48    ICC/PAK)
49        AUS)
50         WI)
51        ENG)
52    ICC/IND)
53        PAK)
54        IND)
56        AUS)
57         SA)
58         SA)
59        ENG)
60         SL)
61        AUS)
62        AUS)
63     ICC/SA)
64        AUS)
65        AUS)
66        ENG)
Name: Country, dtype: object

In [444]:
df["Country"].str.split(pat = ')')

0         [AUS, ]
1         [AUS, ]
2          [SA, ]
3          [WI, ]
5         [ENG, ]
6         [ENG, ]
7         [ENG, ]
8          [WI, ]
9         [ENG, ]
10         [WI, ]
11         [SL, ]
12        [AUS, ]
13        [ENG, ]
14         [WI, ]
15        [ENG, ]
16        [PAK, ]
17     [ICC/SA, ]
19        [ENG, ]
20         [NZ, ]
21         [WI, ]
22        [IND, ]
23        [AUS, ]
24         [SA, ]
25        [IND, ]
26        [ENG, ]
27     [ICC/WI, ]
28        [PAK, ]
29    [ICC/IND, ]
30        [PAK, ]
31        [PAK, ]
32        [AUS, ]
33        [AUS, ]
34        [ZIM, ]
35        [AUS, ]
36         [WI, ]
37        [IND, ]
38        [AUS, ]
39        [AUS, ]
40         [SA, ]
41        [ENG, ]
43        [AUS, ]
44         [NZ, ]
45         [WI, ]
46        [ENG, ]
47         [SL, ]
48    [ICC/PAK, ]
49        [AUS, ]
50         [WI, ]
51        [ENG, ]
52    [ICC/IND, ]
53        [PAK, ]
54        [IND, ]
56        [AUS, ]
57         [SA, ]
58         [SA, ]
59        [ENG, ]
60         [SL, ]
61        [AUS, ]
62        [AUS, ]
63     [ICC/SA, ]
64        [AUS, ]
65        [AUS, ]
66        [ENG, ]
Name: Country, dtype: object

In [445]:
df["Country"] = df["Country"].str.split(pat = ')').str[0]

In [446]:
df["Country"]

0         AUS
1         AUS
2          SA
3          WI
5         ENG
6         ENG
7         ENG
8          WI
9         ENG
10         WI
11         SL
12        AUS
13        ENG
14         WI
15        ENG
16        PAK
17     ICC/SA
19        ENG
20         NZ
21         WI
22        IND
23        AUS
24         SA
25        IND
26        ENG
27     ICC/WI
28        PAK
29    ICC/IND
30        PAK
31        PAK
32        AUS
33        AUS
34        ZIM
35        AUS
36         WI
37        IND
38        AUS
39        AUS
40         SA
41        ENG
43        AUS
44         NZ
45         WI
46        ENG
47         SL
48    ICC/PAK
49        AUS
50         WI
51        ENG
52    ICC/IND
53        PAK
54        IND
56        AUS
57         SA
58         SA
59        ENG
60         SL
61        AUS
62        AUS
63     ICC/SA
64        AUS
65        AUS
66        ENG
Name: Country, dtype: object

In [447]:
df["Player"] = df["Player"].str.split(pat = '(').str[0]

In [448]:
df.head()

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG

In [449]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score              object
Average_Score          float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year              object
End_Year                object
Country                 object
dtype: object

In [450]:
df["High_Score"].str.split(pat = '*')

0       [334]
1     [269, ]
2       [274]
3     [270, ]
5       [194]
6       [243]
7       [256]
8       [207]
9     [336, ]
10    [365, ]
11      [319]
12      [239]
13      [211]
14      [220]
15      [364]
16    [208, ]
17      [224]
19      [122]
20      [251]
21      [183]
22      [227]
23    [247, ]
24      [231]
25    [248, ]
26      [186]
27    [400, ]
28    [280, ]
29      [270]
30      [223]
31      [313]
32      [257]
33    [201, ]
34    [232, ]
35      [195]
36    [203, ]
37    [236, ]
38      [200]
39      [380]
40    [278, ]
41      [254]
43      [205]
44      [190]
45      [291]
46      [278]
47      [374]
48      [329]
49      [215]
50      [261]
51    [182, ]
52      [319]
53    [215, ]
54    [254, ]
56    [329, ]
57    [144, ]
58    [189, ]
59    [144, ]
60      [231]
61      [205]
62      [250]
63      [277]
64      [266]
65      [232]
66      [127]
Name: High_Score, dtype: object

In [451]:
df["High_Score"] = df["High_Score"].str.split(pat = '*').str[0]

In [452]:
df["High_Score"]

0     334
1     269
2     274
3     270
5     194
6     243
7     256
8     207
9     336
10    365
11    319
12    239
13    211
14    220
15    364
16    208
17    224
19    122
20    251
21    183
22    227
23    247
24    231
25    248
26    186
27    400
28    280
29    270
30    223
31    313
32    257
33    201
34    232
35    195
36    203
37    236
38    200
39    380
40    278
41    254
43    205
44    190
45    291
46    278
47    374
48    329
49    215
50    261
51    182
52    319
53    215
54    254
56    329
57    144
58    189
59    144
60    231
61    205
62    250
63    277
64    266
65    232
66    127
Name: High_Score, dtype: object

In [453]:
#Change the data type

In [454]:
df["High_Score"] = df["High_Score"].astype("int")

In [455]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score               int32
Average_Score          float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year              object
End_Year                object
Country                 object
dtype: object

In [456]:
df["Start_Year"] = df["Start_Year"].astype("int")

In [457]:
df["End_Year"] = df["End_Year"].astype("int")

In [458]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score               int32
Average_Score          float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int32
End_Year                 int32
Country                 object
dtype: object

In [459]:
# df["6s"] = df["6s"].astype("float")
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208,56.30,2413,46.66,3,6,1,123,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
19,GE Tyldesley,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,ENG
20,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,755,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
41,JE Root,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44,2012,2024,ENG
43,AR Border,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AUS
44,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ
45,IVA Richards,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182,49.37,619+,30.04,4,3,3,38+,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
54,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND
56,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
57,KC Bland,21,39,5,1669,144,49.08,885+,37.74,3,9,2,123+,20,1961,1966,SA
58,B Mitchell,42,80,9,3471,189,48.88,158+,29.11,8,21,3,41+,1,1929,1949,SA
59,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,51+,0,1893,1905,ENG
60,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
61,RN Harvey,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963,AUS
62,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,AUS
63,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
64,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
65,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS
66,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [460]:
df['6s'].str.split(pat = '+').str[0]

0      6
1      5
2     11
3      1
5      6
6      4
7     27
8      2
9     27
10    32
11    51
12    54
13     8
14    11
15     7
16     1
17    97
19     2
20    24
21     1
22     6
23    16
24     6
25    69
26    26
27    88
28    48
29    21
30    51
31    70
32    73
33     3
34    20
35    39
36    36
37    26
38    20
39    82
40    64
41    44
43    28
44    29
45    84
46     3
47    61
48    48
49    12
50    11
51     0
52    91
53     5
54    26
56    39
57    20
58     1
59     0
60     7
61     1
62    23
63    24
64     0
65     5
66     0
Name: 6s, dtype: object

In [461]:
df['6s']

0       6
1       5
2      11
3       1
5       6
6       4
7      27
8       2
9      27
10    32+
11     51
12     54
13      8
14     11
15      7
16      1
17     97
19      2
20     24
21      1
22      6
23     16
24      6
25     69
26     26
27     88
28     48
29     21
30     51
31     70
32     73
33      3
34     20
35     39
36     36
37     26
38     20
39     82
40     64
41     44
43     28
44     29
45     84
46      3
47     61
48     48
49     12
50     11
51      0
52     91
53      5
54     26
56     39
57     20
58      1
59      0
60      7
61      1
62     23
63     24
64      0
65     5+
66      0
Name: 6s, dtype: object

In [462]:
df['6s'] = df['6s'].str.split(pat = '+').str[0]

In [463]:
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,593+,32,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208,56.30,2413,46.66,3,6,1,123,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
19,GE Tyldesley,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,ENG
20,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,755,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
41,JE Root,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44,2012,2024,ENG
43,AR Border,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AUS
44,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ
45,IVA Richards,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182,49.37,619+,30.04,4,3,3,38+,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
54,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND
56,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
57,KC Bland,21,39,5,1669,144,49.08,885+,37.74,3,9,2,123+,20,1961,1966,SA
58,B Mitchell,42,80,9,3471,189,48.88,158+,29.11,8,21,3,41+,1,1929,1949,SA
59,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,51+,0,1893,1905,ENG
60,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
61,RN Harvey,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963,AUS
62,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,AUS
63,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
64,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
65,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5,1930,1938,AUS
66,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [464]:
df['4s'].str.split(pat = '+').str[1]

0
1     NaN
2
3
5
6
7
8
9
10
11    NaN
12    NaN
13
14
15
16    NaN
17    NaN
19
20    NaN
21
22    NaN
23    NaN
24
25
26    NaN
27    NaN
28
29    NaN
30    NaN
31    NaN
32    NaN
33
34    NaN
35    NaN
36    NaN
37
38    NaN
39    NaN
40    NaN
41    NaN
43    NaN
44    NaN
45
46
47    NaN
48    NaN
49    NaN
50
51
52    NaN
53    NaN
54    NaN
56    NaN
57
58
59
60    NaN
61
62
63    NaN
64
65
66
Name: 4s, dtype: object

In [465]:
df['4s'] = df['4s'].str.split(pat = '+').str[1]

In [466]:
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,NaN,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,,32,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,NaN,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,NaN,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208,56.30,2413,46.66,3,6,1,NaN,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,NaN,97,1995,2013,ICC/SA
19,GE Tyldesley,14,20,2,990,122,55.00,178+,29.21,3,6,2,,2,1921,1929,ENG
20,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,NaN,24,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665+,35.48,4,4,1,,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,NaN,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,NaN,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108+,63.88,9,14,3,,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795,86.79,5,9,1,NaN,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,NaN,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,NaN,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,NaN,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,NaN,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,NaN,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,NaN,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,NaN,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,NaN,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,NaN,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,NaN,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,NaN,64,2004,2018,SA
41,JE Root,146,267,22,12402,254,50.62,21785,56.92,34,64,12,NaN,44,2012,2024,ENG
43,AR Border,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,NaN,28,1978,1994,AUS
44,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,NaN,29,2019,2024,NZ
45,IVA Richards,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,NaN,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,NaN,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,NaN,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488+,40.16,9,22,11,,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182,49.37,619+,30.04,4,3,3,,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,NaN,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,NaN,5,2019,2021,PAK
54,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,NaN,26,2011,2024,IND
56,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,NaN,39,2004,2015,AUS
57,KC Bland,21,39,5,1669,144,49.08,885+,37.74,3,9,2,,20,1961,1966,SA
58,B Mitchell,42,80,9,3471,189,48.88,158+,29.11,8,21,3,,1,1929,1949,SA
59,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,,0,1893,1905,ENG
60,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,NaN,7,2001,2013,SL
61,RN Harvey,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,,1,1948,1963,AUS
62,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,,23,1965,1981,AUS
63,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,NaN,24,2002,2014,ICC/SA
64,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,,0,1924,1934,AUS
65,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,,5,1930,1938,AUS
66,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,,0,1928,1934,ENG

In [467]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score               int32
Average_Score          float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int32
End_Year                 int32
Country                 object
dtype: object

In [468]:
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,NaN,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,,32,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,NaN,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,NaN,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208,56.30,2413,46.66,3,6,1,NaN,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,NaN,97,1995,2013,ICC/SA
19,GE Tyldesley,14,20,2,990,122,55.00,178+,29.21,3,6,2,,2,1921,1929,ENG
20,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,NaN,24,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665+,35.48,4,4,1,,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,NaN,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,NaN,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108+,63.88,9,14,3,,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795,86.79,5,9,1,NaN,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,NaN,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,NaN,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,NaN,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,NaN,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,NaN,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,NaN,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,NaN,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,NaN,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,NaN,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,NaN,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,NaN,64,2004,2018,SA
41,JE Root,146,267,22,12402,254,50.62,21785,56.92,34,64,12,NaN,44,2012,2024,ENG
43,AR Border,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,NaN,28,1978,1994,AUS
44,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,NaN,29,2019,2024,NZ
45,IVA Richards,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,NaN,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,NaN,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,NaN,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488+,40.16,9,22,11,,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182,49.37,619+,30.04,4,3,3,,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,NaN,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,NaN,5,2019,2021,PAK
54,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,NaN,26,2011,2024,IND
56,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,NaN,39,2004,2015,AUS
57,KC Bland,21,39,5,1669,144,49.08,885+,37.74,3,9,2,,20,1961,1966,SA
58,B Mitchell,42,80,9,3471,189,48.88,158+,29.11,8,21,3,,1,1929,1949,SA
59,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,,0,1893,1905,ENG
60,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,NaN,7,2001,2013,SL
61,RN Harvey,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,,1,1948,1963,AUS
62,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,,23,1965,1981,AUS
63,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,NaN,24,2002,2014,ICC/SA
64,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,,0,1924,1934,AUS
65,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,,5,1930,1938,AUS
66,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,,0,1928,1934,ENG

In [469]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score               int32
Average_Score          float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int32
End_Year                 int32
Country                 object
dtype: object

In [470]:
df["Balls_Faced"] = df["Balls_Faced"].str.split(pat = '+').str[0]

In [471]:
df["Balls_Faced"] = df["Balls_Faced"].astype("float")

In [472]:
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,NaN,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558.0,34.59,16,23,2,,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288.0,45.88,4,7,3,,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957.0,42.42,20,35,5,,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,NaN,0.00,15,19,6,,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491.0,38.07,22,24,4,,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063.0,53.58,26,30,12,,32,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882.0,54.19,38,52,11,NaN,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100.0,53.50,32,41,10,NaN,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363.0,46.22,15,28,4,,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,NaN,0.00,15,14,1,,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844.0,39.34,19,33,5,,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208,56.30,2413.0,46.66,3,6,1,NaN,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903.0,45.97,45,58,16,NaN,97,1995,2013,ICC/SA
19,GE Tyldesley,14,20,2,990,122,55.00,178.0,29.21,3,6,2,,2,1921,1929,ENG
20,KS Williamson,100,176,17,8743,251,54.98,17006.0,51.41,32,34,11,NaN,24,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665.0,35.48,4,4,1,,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823.0,59.46,4,3,3,NaN,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247,53.86,13079.0,51.53,24,31,12,NaN,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108.0,63.88,9,14,3,,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248,53.78,29437.0,54.04,51,68,14,,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795.0,86.79,5,9,1,NaN,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400,52.88,19753.0,60.51,34,48,17,NaN,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164.0,45.99,23,43,6,,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258.0,42.51,36,63,8,NaN,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372.0,52.39,24,33,11,NaN,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375.0,52.12,34,33,19,NaN,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782.0,58.72,41,62,17,NaN,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035.0,44.86,3,9,1,,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636.0,45.07,12,27,5,NaN,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436.0,50.13,19,29,12,NaN,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395.0,43.31,30,66,15,NaN,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184.0,43.35,34,45,12,,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461.0,48.64,32,50,22,NaN,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349.0,60.10,30,29,14,NaN,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077.0,54.51,22,46,8,NaN,64,2004,2018,SA
41,JE Root,146,267,22,12402,254,50.62,21785.0,56.92,34,64,12,NaN,44,2012,2024,ENG
43,AR Border,156,265,44,11174,205,50.56,27002.0,41.09,27,63,11,NaN,28,1978,1994,AUS
44,DJ Mitchell,23,37,5,1608,190,50.25,3014.0,53.35,5,10,1,NaN,29,2019,2024,NZ
45,IVA Richards,121,182,12,8540,291,50.23,9613.0,69.77,24,45,10,,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731.0,38.81,17,28,10,,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959.0,51.45,34,50,15,NaN,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345.0,54.02,25,46,15,NaN,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809.0,52.68,11,20,4,NaN,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488.0,40.16,9,22,11,,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182,49.37,619.0,30.04,4,3,3,,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441.0,82.23,23,32,16,NaN,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215,49.16,2445.0,48.26,4,3,2,NaN,5,2019,2021,PAK
54,V Kohli,113,191,11,8848,254,49.15,15924.0,55.56,29,30,14,NaN,26,2011,2024,IND
56,MJ Clarke,115,198,22,8643,329,49.10,15456.0,55.92,28,27,9,NaN,39,2004,2015,AUS
57,KC Bland,21,39,5,1669,144,49.08,885.0,37.74,3,9,2,,20,1961,1966,SA
58,B Mitchell,42,80,9,3471,189,48.88,158.0,29.11,8,21,3,,1,1929,1949,SA
59,Hon.FS Jackson,20,33,4,1415,144,48.79,NaN,0.00,5,6,3,,0,1893,1905,ENG
60,TT Samaraweera,81,132,20,5462,231,48.76,11641.0,46.92,14,30,11,NaN,7,2001,2013,SL
61,RN Harvey,79,137,10,6149,205,48.41,1799.0,43.74,21,24,7,,1,1948,1963,AUS
62,KD Walters,74,125,14,5357,250,48.26,8662.0,49.16,15,33,4,,23,1965,1981,AUS
63,GC Smith,117,205,13,9265,277,48.25,15525.0,59.67,27,38,11,NaN,24,2002,2014,ICC/SA
64,WH Ponsford,29,48,4,2122,266,48.22,3118.0,44.77,7,6,1,,0,1924,1934,AUS
65,SJ McCabe,39,62,5,2748,232,48.21,3217.0,60.02,6,13,4,,5,1930,1938,AUS
66,DR Jardine,22,33,6,1296,127,48.00,2110.0,25.59,1,10,2,,0,1928,1934,ENG

In [473]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score               int32
Average_Score          float64
Balls_Faced            float64
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int32
End_Year                 int32
Country                 object
dtype: object

In [475]:
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,NaN,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558.0,34.59,16,23,2,,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288.0,45.88,4,7,3,,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957.0,42.42,20,35,5,,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,NaN,0.00,15,19,6,,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491.0,38.07,22,24,4,,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063.0,53.58,26,30,12,,32,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882.0,54.19,38,52,11,NaN,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100.0,53.50,32,41,10,NaN,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363.0,46.22,15,28,4,,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,NaN,0.00,15,14,1,,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844.0,39.34,19,33,5,,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208,56.30,2413.0,46.66,3,6,1,NaN,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903.0,45.97,45,58,16,NaN,97,1995,2013,ICC/SA
19,GE Tyldesley,14,20,2,990,122,55.00,178.0,29.21,3,6,2,,2,1921,1929,ENG
20,KS Williamson,100,176,17,8743,251,54.98,17006.0,51.41,32,34,11,NaN,24,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665.0,35.48,4,4,1,,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823.0,59.46,4,3,3,NaN,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247,53.86,13079.0,51.53,24,31,12,NaN,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108.0,63.88,9,14,3,,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248,53.78,29437.0,54.04,51,68,14,,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795.0,86.79,5,9,1,NaN,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400,52.88,19753.0,60.51,34,48,17,NaN,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164.0,45.99,23,43,6,,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258.0,42.51,36,63,8,NaN,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372.0,52.39,24,33,11,NaN,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375.0,52.12,34,33,19,NaN,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782.0,58.72,41,62,17,NaN,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035.0,44.86,3,9,1,,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636.0,45.07,12,27,5,NaN,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436.0,50.13,19,29,12,NaN,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395.0,43.31,30,66,15,NaN,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184.0,43.35,34,45,12,,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461.0,48.64,32,50,22,NaN,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349.0,60.10,30,29,14,NaN,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077.0,54.51,22,46,8,NaN,64,2004,2018,SA
41,JE Root,146,267,22,12402,254,50.62,21785.0,56.92,34,64,12,NaN,44,2012,2024,ENG
43,AR Border,156,265,44,11174,205,50.56,27002.0,41.09,27,63,11,NaN,28,1978,1994,AUS
44,DJ Mitchell,23,37,5,1608,190,50.25,3014.0,53.35,5,10,1,NaN,29,2019,2024,NZ
45,IVA Richards,121,182,12,8540,291,50.23,9613.0,69.77,24,45,10,,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731.0,38.81,17,28,10,,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959.0,51.45,34,50,15,NaN,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345.0,54.02,25,46,15,NaN,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809.0,52.68,11,20,4,NaN,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488.0,40.16,9,22,11,,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182,49.37,619.0,30.04,4,3,3,,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441.0,82.23,23,32,16,NaN,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215,49.16,2445.0,48.26,4,3,2,NaN,5,2019,2021,PAK
54,V Kohli,113,191,11,8848,254,49.15,15924.0,55.56,29,30,14,NaN,26,2011,2024,IND
56,MJ Clarke,115,198,22,8643,329,49.10,15456.0,55.92,28,27,9,NaN,39,2004,2015,AUS
57,KC Bland,21,39,5,1669,144,49.08,885.0,37.74,3,9,2,,20,1961,1966,SA
58,B Mitchell,42,80,9,3471,189,48.88,158.0,29.11,8,21,3,,1,1929,1949,SA
59,Hon.FS Jackson,20,33,4,1415,144,48.79,NaN,0.00,5,6,3,,0,1893,1905,ENG
60,TT Samaraweera,81,132,20,5462,231,48.76,11641.0,46.92,14,30,11,NaN,7,2001,2013,SL
61,RN Harvey,79,137,10,6149,205,48.41,1799.0,43.74,21,24,7,,1,1948,1963,AUS
62,KD Walters,74,125,14,5357,250,48.26,8662.0,49.16,15,33,4,,23,1965,1981,AUS
63,GC Smith,117,205,13,9265,277,48.25,15525.0,59.67,27,38,11,NaN,24,2002,2014,ICC/SA
64,WH Ponsford,29,48,4,2122,266,48.22,3118.0,44.77,7,6,1,,0,1924,1934,AUS
65,SJ McCabe,39,62,5,2748,232,48.21,3217.0,60.02,6,13,4,,5,1930,1938,AUS
66,DR Jardine,22,33,6,1296,127,48.00,2110.0,25.59,1,10,2,,0,1928,1934,ENG

In [477]:
df[df["Balls_Faced"].isna() ==1]

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
8,ED Weekes,48,81,5,4455,207,58.61,NaN,0.0,15,19,6,,2,1948,1958,WI
14,CL Walcott,44,74,7,3798,220,56.68,NaN,0.0,15,14,1,,11,1948,1960,WI
59,Hon.FS Jackson,20,33,4,1415,144,48.79,NaN,0.0,5,6,3,,0,1893,1905,ENG

In [479]:
df["Balls_Faced"] = df["Balls_Faced"].fillna(0)

In [481]:
df["Balls_Faced"] = df["Balls_Faced"].astype("int")

In [ ]:
pd.set_option('display.max_rows', None)

In [483]:
df

,Player,Matches,Innings,Not_Outs,Runs,High_Score,Average_Score,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,End_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,NaN,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,,32,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,NaN,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,NaN,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208,56.30,2413,46.66,3,6,1,NaN,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,NaN,97,1995,2013,ICC/SA
19,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,,2,1921,1929,ENG
20,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,NaN,24,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,NaN,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,NaN,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795,86.79,5,9,1,NaN,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,NaN,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,NaN,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,NaN,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,NaN,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,NaN,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,NaN,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,NaN,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,NaN,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,NaN,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,NaN,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,NaN,64,2004,2018,SA
41,JE Root,146,267,22,12402,254,50.62,21785,56.92,34,64,12,NaN,44,2012,2024,ENG
43,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,NaN,28,1978,1994,AUS
44,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,NaN,29,2019,2024,NZ
45,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,NaN,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,NaN,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,NaN,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,NaN,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,NaN,5,2019,2021,PAK
54,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,NaN,26,2011,2024,IND
56,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,NaN,39,2004,2015,AUS
57,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,,20,1961,1966,SA
58,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,,1,1929,1949,SA
59,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,,0,1893,1905,ENG
60,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,NaN,7,2001,2013,SL
61,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,,1,1948,1963,AUS
62,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,,23,1965,1981,AUS
63,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,NaN,24,2002,2014,ICC/SA
64,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,,0,1924,1934,AUS
65,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,,5,1930,1938,AUS
66,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,,0,1928,1934,ENG

In [485]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score               int32
Average_Score          float64
Balls_Faced              int32
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int32
End_Year                 int32
Country                 object
dtype: object

In [ ]:
df['4s'].str.split(pat = "+")

In [487]:
df.dtypes

Player                  object
Matches                  int64
Innings                  int64
Not_Outs                 int64
Runs                     int64
High_Score               int32
Average_Score          float64
Balls_Faced              int32
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int32
End_Year                 int32
Country                 object
dtype: object

In [ ]:
#create Career_Length field using start_year and end_year fields

In [495]:
df["Career_Length"] = df["End_Year"] - df["Start_Year"]

In [ ]:
#Average career length

In [501]:
df["Career_Length"].mean()

13.031746031746032

In [503]:
#Average batting strike rate who played over 10 years

In [507]:
df[df["Career_Length"] > 10] ["Batting_Strike_Rate"].mean()

47.95590909090909

In [509]:
#find the number of cricketers who played before 1960

In [517]:
df[df["Start_Year"] < 1960] ["Player"].count()

23

In [519]:
#max highest inns score by country

In [531]:
df.groupby("Country") ["High_Score"].max().to_frame("HighScoreByCountry").reset_index().sort_values("HighScoreByCountry", ascending = False
                                                                                                )

    Country  HighScoreByCountry
5    ICC/WI                 400
0       AUS                 380
10       SL                 374
11       WI                 365
1       ENG                 364
3   ICC/PAK                 329
2   ICC/IND                 319
8       PAK                 313
9        SA                 278
4    ICC/SA                 277
6       IND                 254
7        NZ                 251
12      ZIM                 232

In [533]:
# Hundreds, fifties, ducks AVG by country

In [535]:
df.groupby("Country") [["100", "50", "0"]].mean()

               100         50          0
Country
AUS      20.625000  28.375000   8.562500
ENG      12.692308  21.230769   4.307692
ICC/IND  29.500000  47.500000  12.000000
ICC/PAK  25.000000  46.000000  15.000000
ICC/SA   36.000000  48.000000  13.500000
ICC/WI   34.000000  48.000000  17.000000
IND      29.500000  36.500000  10.750000
NZ       18.500000  22.000000   6.000000
PAK      17.600000  23.600000   7.800000
SA        9.800000  20.200000   3.400000
SL       28.666667  44.000000  12.333333
WI       16.625000  25.625000   7.250000
ZIM      12.000000  27.000000   5.000000